spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    driver:
      class:
        name: org.postgresql.Driver
  cloud:
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
      kafka:
        binder:
          brokers:
            - localhost:9092


api:
  security:
    token:
      secret: "mySecretKey"

logging:
  level:
    org:
      springframework:
        security: DEBUG
